# Generated by Django 5.1.1 on 2024-10-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file',
            new_name='url',
        ),
        migrations.AddField(
            model_name='files',
            name='file_name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
