# Generated by Django 5.1.1 on 2024-10-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_file_files_url_files_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='title',
        ),
    ]
